// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAmxIIi_GKD11d6vHY3QPn90elDOLqBa-g',
    appId: '1:57927787787:web:70865f668b626cbf2aae0e',
    messagingSenderId: '57927787787',
    projectId: 'myewaste-eed23',
    authDomain: 'myewaste-eed23.firebaseapp.com',
    databaseURL: 'https://myewaste-eed23-default-rtdb.firebaseio.com',
    storageBucket: 'myewaste-eed23.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCNpjYX4sqkCSJgurrN9tgwZ3MTSZx8mVU',
    appId: '1:57927787787:android:f63bc93e7a473a4d2aae0e',
    messagingSenderId: '57927787787',
    projectId: 'myewaste-eed23',
    databaseURL: 'https://myewaste-eed23-default-rtdb.firebaseio.com',
    storageBucket: 'myewaste-eed23.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAQZL4g8ap3pu21ZG3SZnVIBmvN0rlMCw0',
    appId: '1:57927787787:ios:1a2b2c07e3be84c22aae0e',
    messagingSenderId: '57927787787',
    projectId: 'myewaste-eed23',
    databaseURL: 'https://myewaste-eed23-default-rtdb.firebaseio.com',
    storageBucket: 'myewaste-eed23.appspot.com',
    iosClientId: '57927787787-g39j7hcnavnm23balsv55a57knaglpi2.apps.googleusercontent.com',
    iosBundleId: 'com.example.quizApp',
  );
}
